### ISSUE TITLE
Does not support webpack 4

### ISSUE THREAD

**Issue by ranyitz** [wix/stylable-integration#30]
Webpack 4 was officially [released](https://github.com/webpack/webpack/releases/tag/v4.0.0) and has some breaking changes for loaders and plugins, here is the [migration guide](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202).

When using the webpack plugin it throws errors, I think it related to chunk Graph and chunkGroup changes. You can look at [this PR](https://github.com/webpack/webpack/pull/6279/files) for reference.

This is currently the only thing that stops us from migrating to webpack 4.

**Comment by yavorsky** [comment]
I've this error when trying to run `stylable-loader` with webpack 4:

```
Error: Chunk.parents: Use ChunkGroup.getParents() instead
    at Chunk.get (/Users/artemy/Development/OSS/wix-haste/haste-preset-yoshi/node_modules/webpack/lib/Chunk.js:438:9)
    at /Users/artemy/Development/OSS/wix-haste/haste-preset-yoshi/node_modules/stylable-integration/dist/src/webpack-loader.js:150:75
    at Array.map (<anonymous>)
    at /Users/artemy/Development/OSS/wix-haste/haste-preset-yoshi/node_modules/stylable-integration/dist/src/webpack-loader.js:149:36
```

**Comment by idoros** [comment]
We are currently evaluating adding support for Webpack 4, hope to have more on the matter soon.

**Comment by aarnoldaas** [comment]
Hi! is there any news? Stylable now used by wix-style-react. This stops a lot of project migrating to yoshi@2 (webpack4)

**Comment by Scott-MacD** [comment]
Also hoping to see this updated. Trying to get started evaluating stylable as part of our new stack, however if we choose to go down the webpack route we're stuck with stylable not supporting webpack 4, and some of the other tools in our build process not compatible with webpack 3.

**Comment by Scott-MacD** [comment]
How does one set up the loader for the new plugin?

**Comment by Scott-MacD** [comment]
Got this working without having to specify any sort of loader following the experimental repo. Pretty sure that was what I tried in the first place when I had issues, but that was on a different machine. I'll confirm if everything is working properly on that machine as well when I'm back in the office on Monday.

Awesome work guys!

**Comment by tomrav** [comment]
You are correct in saying that In the new integration, you do not need to configure the loader. We have decided to lock down the file type suffix to `.st.css`. 

Glad to hear you've got it working, please let us know if you're encountering any unexpected behavior.

**Comment by Scott-MacD** [comment]
Confirming this is all working as expected. I'm not able to reproduce the issue I had initially, so not sure what I did wrong, but I don't think it's any bug with the new plugin.
